### ISSUE TITLE
How can I settings on window 11 and powershell

### ISSUE THREAD

**Issue by Rujipas-Thongpao** [roberte777/ronsai#1]
![image](https://github.com/user-attachments/assets/e65fec88-8869-4b6d-beaf-36b10e456c5e)

Hi, I found this repo because I also couldn't setting up the original bonsai. So I try this repo because this one use rust. It run but it look like it do nothing (?). I use `rbonsai -l -v`. How can I settings on window 11 and powershell? Thanks!

**Comment by roberte777** [comment]
Thanks for notifying me of this. I only use windows for gaming, so I hadn't tested. The issue was that the enter key when you run the program on windows actually gets sent as an event in crossterm, whereas on linux only key presses after that initial enter press would be registered. This was causing the program to exit early on windows. I just pushed up a new version (0.1.3). Do a fresh install and let me know if that fixes :D

**Comment by Rujipas-Thongpao** [comment]
https://github.com/user-attachments/assets/c9c4edce-8b52-4f53-925b-9ad1fba1de24

Thanks! But it work only when I using `cargo run -- -l -v` but won't work on normal `rbonsai -l -v`


![image](https://github.com/user-attachments/assets/35322e82-129c-465d-add8-4892a730a4d4)

**Comment by Rujipas-Thongpao** [comment]
I also found another problem. When I click on other program, it stop immediately
 

https://github.com/user-attachments/assets/be9eb37b-394b-4c3e-834e-129a2d37a2ff

**Comment by roberte777** [comment]
Thank you for the videos! They are quite helpful when trying to diagnose issues.

I want to address the new issue you brought up first. I was not correctly filtering out mouse events, so when you clicked, it would cancel rbonsai. I am now only doing so on keyboard events. Mouse events should now not exit rbonsai. I pushed a new patch with this fix as well (v0.1.4).

 As for the difference between rbonsai and cargo run, I am not able to replicate a difference between the two on my machine. They should be identical, and on my windows machine they behave the same. The code you are running with cargo run should be the same code that you're running when you type cargo run -- -l -v. Did you run `cargo install rbonsai --locked --force`?

**Comment by Rujipas-Thongpao** [comment]
https://github.com/user-attachments/assets/8d5c229c-ef04-4b3f-a4d0-56f8549ffe27

It works! Thanks for replying my issues. now I can watch bonsai grows on my terminal. Great project :D
